apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tc2-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/BionicMJallday/tech-challenge-2.git
    targetRevision: gitops
    path: helm/tc2-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true